apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-tata
  namespace: argocd
spec:
  destination:
    namespace: web
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://github.com/vishesh-acefone/tata"
      path: manifests
      targetRevision: main
    
    - repoURL: "https://github.com/vishesh-acefone/tata-config"
      path: web
      targetRevision: main

  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false