apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-tata-argocd
  namespace: argocd
spec:
  destination:
    namespace: web
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/vishesh-acefone/tata"
    targetRevision: main
  project: default
  # syncPolicy:
  #   automated:
  #     prune: false
  #     selfHeal: false